In [3]:
import numpy as np

In [ ]:
data=np.random.randint(0,10,5)

In [ ]:
data

array([1, 0, 9, 6, 4])

In [ ]:
data+10

array([11, 10, 19, 16, 14])

In [ ]:
x=np.random.randint(0,18,(3,3))

In [ ]:
x

array([[ 6,  8,  8],
       [ 2,  6, 14],
       [ 2,  5, 16]])

In [ ]:
y=np.random.randint(0,10,(1,3))

In [ ]:
y

array([[2, 3, 9]])

In [ ]:
x+y

array([[ 8, 11, 17],
       [ 4,  9, 23],
       [ 4,  8, 25]])

In [ ]:
x=np.random.randint(0,10,(5,1))

In [ ]:
x

array([[7],
       [4],
       [8],
       [0],
       [4]])

In [ ]:
y=np.random.randint(0,10,4)

In [ ]:
y

array([2, 7, 8, 8])

In [ ]:
x+y

array([[ 9, 14, 15, 15],
       [ 6, 11, 12, 12],
       [10, 15, 16, 16],
       [ 2,  7,  8,  8],
       [ 6, 11, 12, 12]])

In [ ]:
data=np.loadtxt("/content/sample_data/sample.txt")

In [ ]:
data

array([ 123456.,  732652.,  873845.,  563673., 5467376.])

In [ ]:
data.shape

(5,)

In [ ]:
data.sum()

np.float64(7761002.0)

In [ ]:
data-3

array([ 123453.,  732649.,  873842.,  563670., 5467373.])

In [ ]:
data*2

array([  246912.,  1465304.,  1747690.,  1127346., 10934752.])

In [ ]:
data=np.loadtxt("/content/sample_data/sample.file1.txt")

In [ ]:
data

array([1462576., 6323398., 6748533., 5678993.,  997665., 9847357.,
       1111111., 2222222., 3333333., 4444444., 5555555., 6666666.,
       7777777., 8888888., 9999999., 1010101.])

In [ ]:
data=np.loadtxt("/content/sample_data/sample file.txt")

In [ ]:
data

array([1462576., 6323398., 6748533., 5678993.,  997665., 9847357.,
       1111111., 2222222., 3333333., 4444444., 5555555., 6666666.,
       7777777., 8888888., 9999999., 1010101.])

In [4]:
data=np.random.randint(0,10,5)


In [5]:
data

array([4, 7, 4, 8, 5])

In [6]:
data.cumsum()

array([ 4, 11, 15, 23, 28])

In [7]:
data.cumprod()

array([   4,   28,  112,  896, 4480])

In [9]:
data=np.random.randint(0,10,(3,3))

In [10]:
data

array([[4, 7, 0],
       [2, 0, 1],
       [4, 3, 9]])

In [11]:
data.cumsum(axis=1)

array([[ 4, 11, 11],
       [ 2,  2,  3],
       [ 4,  7, 16]])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
a=np.random.choice([10,20,30,40,50],size=3)
a

array([20, 10, 30])

In [19]:
a=np.random.choice([10,20,30,40,50],size=3,replace=True)
a

array([10, 40, 20])

In [21]:
a=np.random.choice([10,20,30,40,50],size=3,replace=False)
a

array([30, 50, 10])