In [ ]:
import numpy as np

In [ ]:
list(),str(),tuple(),set(),dict()

([], '', (), set(), {})

In [ ]:
y=np.array([1,2,3])

In [ ]:
x=[1,2,3]

In [ ]:
type(x),type(y)

(list, numpy.ndarray)

In [ ]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
y/2

array([0.5, 1. , 1.5])

In [ ]:
x=[1,5,19,"data science"]

In [ ]:
x

[1, 2, 3, 'data science']

In [ ]:
type(x[0]),type(x[1]),type(x[2]),type(x[3])

(int, int, int, str)

In [ ]:
y=np.array([1,35,7,'data science'])

In [ ]:
type(y[0]),type(y[1]),type(y[2]),type(y[3])

(numpy.str_, numpy.str_, numpy.str_, numpy.str_)

In [ ]:
for i in range(1,10):
  print(np.random.randint(0,8))

7
2
2
3
2
3
1
1
2


In [ ]:
np.random.randint(0,10,(5,5))

array([[8, 8, 5, 0, 0],
       [7, 6, 5, 9, 5],
       [6, 3, 4, 2, 8],
       [2, 9, 8, 6, 3],
       [9, 7, 7, 6, 1]])

In [ ]:
data=np.random.randint(0,60,(5,4))

In [ ]:
data

array([[35,  5, 12, 58],
       [39,  3,  6, 33],
       [21, 53, 16, 15],
       [26, 35, 43, 59],
       [42, 57, 38,  6]])

In [ ]:
data[0:3,2:3]

array([[12],
       [ 6],
       [16]])

In [ ]:
data[-5:-3,-4:-2]

array([[35,  5],
       [39,  3]])

In [ ]:
data[1:4,2:4]

array([[ 6, 33],
       [16, 15],
       [43, 59]])

In [ ]:
data=np.random.randint(0,10,(5,5))

In [ ]:
data

array([[6, 7, 2, 5, 5],
       [5, 3, 8, 2, 6],
       [8, 1, 9, 0, 3],
       [4, 1, 6, 9, 0],
       [3, 8, 4, 2, 6]])

In [ ]:
data[2:5,3:4]

array([[0],
       [9],
       [2]])

In [ ]:
data[-4:-1,-3:-2]

array([[8],
       [9],
       [6]])

In [ ]:
data[4:5,2:5]

array([[4, 2, 6]])

In [ ]:
data[0,:]

array([6, 7, 2, 5, 5])

In [ ]:
data[:,0]

array([6, 5, 8, 4, 3])

In [ ]:
data.shape

(5, 5)

In [ ]:
data.T

array([[6, 5, 8, 4, 3],
       [7, 3, 1, 1, 8],
       [2, 8, 9, 6, 4],
       [5, 2, 0, 9, 2],
       [5, 6, 3, 0, 6]])

In [ ]:
data.size

25

In [ ]:
data*2

array([[12, 14,  4, 10, 10],
       [10,  6, 16,  4, 12],
       [16,  2, 18,  0,  6],
       [ 8,  2, 12, 18,  0],
       [ 6, 16,  8,  4, 12]])

In [ ]:
data+2

array([[ 8,  9,  4,  7,  7],
       [ 7,  5, 10,  4,  8],
       [10,  3, 11,  2,  5],
       [ 6,  3,  8, 11,  2],
       [ 5, 10,  6,  4,  8]])

In [ ]:
data-2

array([[ 4,  5,  0,  3,  3],
       [ 3,  1,  6,  0,  4],
       [ 6, -1,  7, -2,  1],
       [ 2, -1,  4,  7, -2],
       [ 1,  6,  2,  0,  4]])

In [ ]:
data/2

array([[3. , 3.5, 1. , 2.5, 2.5],
       [2.5, 1.5, 4. , 1. , 3. ],
       [4. , 0.5, 4.5, 0. , 1.5],
       [2. , 0.5, 3. , 4.5, 0. ],
       [1.5, 4. , 2. , 1. , 3. ]])

In [ ]:
data//2

array([[3, 3, 1, 2, 2],
       [2, 1, 4, 1, 3],
       [4, 0, 4, 0, 1],
       [2, 0, 3, 4, 0],
       [1, 4, 2, 1, 3]])

In [ ]:
data**2

array([[36, 49,  4, 25, 25],
       [25,  9, 64,  4, 36],
       [64,  1, 81,  0,  9],
       [16,  1, 36, 81,  0],
       [ 9, 64, 16,  4, 36]])

In [ ]:
x=np.random.randint(0,5,(2,3))
y=np.random.randint(0,6,(2,3))

In [ ]:
x

array([[2, 4, 4],
       [2, 2, 0]])

In [ ]:
y

array([[4, 2, 3],
       [1, 5, 5]])

In [ ]:
np.add(x,2)

array([[4, 6, 6],
       [4, 4, 2]])

In [ ]:
np.multiply(y,2)

array([[ 8,  4,  6],
       [ 2, 10, 10]])

In [ ]:
np.divide(x,5)

array([[0.4, 0.8, 0.8],
       [0.4, 0.4, 0. ]])

In [ ]:
np.floor_divide(x,3)

array([[0, 1, 1],
       [0, 0, 0]])

In [ ]:
np.exp(x,)

array([[ 7.3890561 , 54.59815003, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  1.        ]])

In [ ]:
np.pow(x,3)

array([[ 8, 64, 64],
       [ 8,  8,  0]])

In [ ]:
np.random.rand(5,4)

array([[0.99009364, 0.94660461, 0.05183867, 0.25782633],
       [0.22535328, 0.8655541 , 0.63150269, 0.83468726],
       [0.9443004 , 0.88517542, 0.27526294, 0.70714412],
       [0.24411039, 0.78603641, 0.02680558, 0.51977012],
       [0.55229914, 0.06069701, 0.17371884, 0.27708627]])

In [ ]:
np.random.rand(5,5)

array([[0.83868103, 0.17698782, 0.58414067, 0.65153282, 0.61791679],
       [0.5413374 , 0.34320165, 0.66662196, 0.56290811, 0.19582029],
       [0.55047807, 0.84773273, 0.67163448, 0.81067366, 0.04535455],
       [0.2012757 , 0.3962808 , 0.34969444, 0.12500272, 0.08156589],
       [0.56695053, 0.99816904, 0.22359756, 0.15739145, 0.51374823]])

In [ ]:
np.random.randn(5,5).std()

np.float64(1.1101519234879056)

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
data=np.random.randint(0,5,(5,5))

In [ ]:
data

array([[3, 4, 1, 3, 1],
       [2, 3, 1, 3, 2],
       [4, 0, 4, 1, 4],
       [3, 1, 0, 0, 2],
       [1, 4, 1, 3, 4]])

In [ ]:
print(data.sum())
print(data.min())
print(data.max())

55
0
4


In [ ]:
data.argmax()

np.int64(1)

In [ ]:
data=np.random.randint(0,6,(3,3))

In [ ]:
data

array([[3, 4, 1, 3, 1],
       [2, 3, 1, 3, 2],
       [4, 0, 4, 1, 4],
       [3, 1, 0, 0, 2],
       [1, 4, 1, 3, 4]])

In [ ]:
data.sum(axis=1)

array([12, 11, 13,  6, 13])

In [ ]:
data.sum(axis=0)

array([13, 12,  7, 10, 13])

In [ ]:
data.argmin(axis=1)

array([2, 2, 1, 2, 0])

In [ ]:
data.max(axis=0)

array([4, 4, 4, 3, 4])