In [ ]:
import numpy as np

In [ ]:
data=np.random.randint(0,10,6)

In [ ]:
data

array([3, 1, 1, 3, 8, 9])

In [ ]:
data+3

array([ 6,  4,  4,  6, 11, 12])

In [ ]:
x=np.random.randint(0,10,(3,3))

In [ ]:
x

array([[8, 4, 1],
       [6, 3, 9],
       [1, 8, 9]])

In [ ]:
y=np.random.randint(0,10,(1,3))

In [ ]:
y

array([[2, 2, 8]])

In [ ]:
x

array([[8, 4, 1],
       [6, 3, 9],
       [1, 8, 9]])

In [ ]:
[1,2,3]
[1,2,3]
[1,2,3]

[1, 2, 3]

In [ ]:
y

array([[2, 2, 8]])

In [ ]:
x+y

array([[10,  6,  9],
       [ 8,  5, 17],
       [ 3, 10, 17]])

In [ ]:
x=np.random.randint(0,10,(4,1))

In [ ]:
x

array([[1],
       [9],
       [0],
       [8]])

In [ ]:
y=np.random.randint(0,10,4)

In [ ]:
x

array([[1],
       [9],
       [0],
       [8]])

In [ ]:
y

array([3, 9, 0, 1])

In [ ]:
[3,4,5,6,]
[3,4,5,6,]
[3,4,5,6,]
[3,4,5,6,]

[3, 4, 5, 6]

In [ ]:
5555
1111
1111
5555

5555

In [ ]:
x+y

array([[ 4, 10,  1,  2],
       [12, 18,  9, 10],
       [ 3,  9,  0,  1],
       [11, 17,  8,  9]])

In [ ]:
x

array([[1],
       [9],
       [0],
       [8]])

In [ ]:
y

array([3, 9, 0, 1])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
data

array([3, 1, 1, 3, 8, 9])